# Generated by Django 3.1 on 2020-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('publishedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
