# Generated by Django 3.1 on 2020-08-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='age',
            new_name='price',
        ),
    ]
